var userData =
{
login: "mikefausz",
id: 16927182,
avatar_url: "https://avatars.githubusercontent.com/u/16927182?v=3",
gravatar_id: "",
url: "https://api.github.com/users/mikefausz",
html_url: "https://github.com/mikefausz",
followers_url: "https://api.github.com/users/mikefausz/followers",
following_url: "https://api.github.com/users/mikefausz/following{/other_user}",
gists_url: "https://api.github.com/users/mikefausz/gists{/gist_id}",
starred_url: "https://api.github.com/users/mikefausz/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/mikefausz/subscriptions",
organizations_url: "https://api.github.com/users/mikefausz/orgs",
repos_url: "https://api.github.com/users/mikefausz/repos",
events_url: "https://api.github.com/users/mikefausz/events{/privacy}",
received_events_url: "https://api.github.com/users/mikefausz/received_events",
type: "User",
site_admin: false,
name: "Mike Fausz",
company: null,
blog: null,
location: "Charleston, SC, USA",
email: null,
hireable: null,
bio: null,
public_repos: 10,
public_gists: 0,
followers: 1,
following: 1,
created_at: "2016-01-27T21:20:13Z",
updated_at: "2016-02-17T18:02:35Z"
};
